In [ ]:
import pandas as pd
import numpy as np

# Leemos el archivo TXT indicando que:
# skiprows = Sirve para que se salte los primeros 18 renglones de texto informativo
# sep '\s' = Lo usamos para que los datos están separados por espacios en blanco
# names []= Le indicamos los nombres que usaremos para cada columna
# encoding = Utilizamos el formato 'latin-1' para que no fallen los acentos o símbolos
df = pd.read_csv('./Dataset/25001.txt', skiprows=18, sep='\s+', names=['Fecha', 'Precip', 'Evap', 'Tmax', 'Tmin'], encoding='latin-1')

# Mostramos un aviso de que todo salió bien y vemos los primeros 10 renglones
print("Archivo cargado con éxito")
df.head(10)

Archivo cargado con éxito

<>:9: SyntaxWarning: invalid escape sequence '\s'
<>:9: SyntaxWarning: invalid escape sequence '\s'
C:\Users\luis_\AppData\Local\Temp\ipykernel_62288\3151756258.py:9: SyntaxWarning: invalid escape sequence '\s'
  df = pd.read_csv('./Dataset/25001.txt', skiprows=19, sep='\s+', names=['Fecha', 'Precip', 'Evap', 'Tmax', 'Tmin'])

        Fecha Precip  Evap  Tmax  Tmin
0  01/01/1961      0  Nulo    25    13
1  02/01/1961      0  Nulo  27.5    14
2  03/01/1961      0  Nulo    31    11
3  04/01/1961      0  Nulo    32    13
4  05/01/1961      0  Nulo    29    14
5  06/01/1961      0  Nulo    24  14.5
6  07/01/1961      0  Nulo  28.5    10
7  08/01/1961      0  Nulo    32    12
8  09/01/1961      0  Nulo  33.5    11
9  10/01/1961      0  Nulo  32.5   9.5

In [75]:
# Quitamos la palabra "Nulo"
df = df.replace('Nulo', np.nan)

# Convertimos la columna de fecha a formato datetime
# coerce = Si encuentra basura o texto que no entiende, en lugar de marcar error, simplemente lo marca como NaT
df['Fecha'] = pd.to_datetime(df['Fecha'], errors='coerce')

# Se borran los elementos que no tengan una fecha valida o que sean NaT (Not at Time)
df = df.dropna(subset=['Fecha'])

# Convertimos las columnas de datos a números
cols_num = ['Precip', 'Evap', 'Tmax', 'Tmin']
df[cols_num] = df[cols_num].apply(pd.to_numeric, errors='coerce')

df.head(10)

C:\Users\santi\AppData\Local\Temp\ipykernel_3984\3799765257.py:6: UserWarning: Could not infer format, so each element will be parsed individually, falling back to `dateutil`. To ensure parsing is consistent and as-expected, please specify a format.
  df['Fecha'] = pd.to_datetime(df['Fecha'], errors='coerce')

        Fecha  Precip  Evap  Tmax  Tmin
1  1961-01-01     0.0   NaN  25.0  13.0
2  1961-02-01     0.0   NaN  27.5  14.0
3  1961-03-01     0.0   NaN  31.0  11.0
4  1961-04-01     0.0   NaN  32.0  13.0
5  1961-05-01     0.0   NaN  29.0  14.0
6  1961-06-01     0.0   NaN  24.0  14.5
7  1961-07-01     0.0   NaN  28.5  10.0
8  1961-08-01     0.0   NaN  32.0  12.0
9  1961-09-01     0.0   NaN  33.5  11.0
10 1961-10-01     0.0   NaN  32.5   9.5

In [ ]:
# Nos aseguramos de tener una columna solo con el Año
df['Año'] = df['Fecha'].dt.year

# Creamos una tabla temporal que contiene True si el dato falta y False si el dato existe
tabla_nulos = df[['Precip', 'Evap', 'Tmax', 'Tmin']].isnull()

# Agrupamos esa tabla de "Trues y Falses" por el Año y los sumamos
# Esto nos dará el total de faltantes por cada año de forma automática
faltantes_por_anio = tabla_nulos.groupby(df['Año']).sum()

# Mostramos el resultado
print("Cantidad de datos faltantes por cada año:")
display(faltantes_por_anio)

# También podemos ver el total de días que faltan en todos los registros por cada columna
print("\nTotal de días con datos faltantes en todo el registro:")
print(df[['Precip', 'Evap', 'Tmax', 'Tmin']].isnull().sum())

Cantidad de datos faltantes por cada año:

      Precip  Evap  Tmax  Tmin
Año
1961       0    61     0     0
1962       0     2     0     0
1963       0     4     0     0
1964       1     0     0     0
1965       0     4     0     0
1966       1     3     0     0
1967       0     2     0     0
1968       0     1     0     0
1969      30     1     1     1
1970       0     0     1     1
1971       0     0     0     0
1972       0     0     0     0
1973       0     0     0     0
1974       0     2     0     0
1975       0     1     0     0
1976       0     0     0     0
1977       0     1     0     0
1978       0     0     0     0
1979       0     0     0     0
1980       0     0     0     0
1981       0     0     0     0
1982       0     2     0     0
1983       0     0     0     0
1984       0     0     0     0
1985       0     0     0     0
1986       0     0     0     0
1987       0     0     0     0
1988       0     0     0     0
1989       0     0     0     0
1990       0     0     0     0
1991       1     0     0     0
1992       1     3     1     1
1993       0     0     0     0
1994       0     0     0     0
1995       0     0     0     0
1996       0     0     0     0
1997       0     0     0     0
1998       0     0     0     0
1999       3     2     1     1
2000       0    30     0     0
2001       2     0     0     0
2002       0     0     0     0
2003       0     2     1     1
2004       0     0     0     0
2005       0     1     0     0
2006       0     1     0     0
2007       0     1     0     0
2008       0     0     0     0
2009       0   128     0     0
2010       0     1     0     0
2011       0     1     0     0
2012       1     6     0     1
2013       0     2     0     0
2014       0     2     0     0
2015       0     2     0     0
2016       0     3     0     0
2017       0     2     0     0
2018       0     1     0     0

Total de días con datos faltantes en todo el registro:
Precip     40
Evap      272
Tmax        5
Tmin        6
dtype: int64

In [76]:
df.info()

<class 'pandas.core.frame.DataFrame'>
Index: 19574 entries, 1 to 19574
Data columns (total 5 columns):
 #   Column  Non-Null Count  Dtype
---  ------  --------------  -----
 0   Fecha   19574 non-null  datetime64[ns]
 1   Precip  19534 non-null  float64
 2   Evap    19302 non-null  float64
 3   Tmax    19569 non-null  float64
 4   Tmin    19568 non-null  float64
dtypes: datetime64[ns](1), float64(4)
memory usage: 917.5 KB

In [77]:
df.describe()

,Fecha,Precip,Evap,Tmax,Tmin
count,19574,19534.000000,19302.000000,19569.000000,19568.000000
mean,1989-03-03 02:58:54.893225728,2.217452,4.882157,34.468808,16.657420
min,1961-01-01 00:00:00,0.000000,0.000000,18.000000,-2.500000
25%,1974-05-26 06:00:00,0.000000,3.200000,32.500000,11.000000
50%,1987-11-18 12:00:00,0.000000,4.500000,35.000000,16.500000
75%,2004-04-09 18:00:00,0.000000,6.500000,37.000000,23.000000
max,2018-12-07 00:00:00,217.400000,15.600000,45.500000,29.000000
std,NaN,9.015782,2.279340,3.430054,6.248605

In [85]:
# Ordenar por fecha 
df = df.sort_values("Fecha")
df

           Fecha  Precip  Evap  Tmax  Tmin
1     1961-01-01     0.0   NaN  25.0  13.0
32    1961-01-02     0.0   NaN  30.0  12.0
60    1961-01-03     0.0   NaN  37.5   9.0
91    1961-01-04     0.0   6.6  32.0  11.5
121   1961-01-05     0.0   8.0  37.5  15.0
...          ...     ...   ...   ...   ...
19436 2018-12-02     0.0   4.6  34.0   9.5
19464 2018-12-03     0.0   6.0  35.5  11.0
19495 2018-12-04     0.0   5.9  37.0  14.5
19525 2018-12-06    20.0   8.0  37.0  24.0
19555 2018-12-07     0.0   4.7  36.0  20.5

[19574 rows x 5 columns]

In [81]:
# Cantidad de nulos por columna
df.isnull().sum()

Fecha       0
Precip     40
Evap      272
Tmax        5
Tmin        6
dtype: int64

In [87]:
# Mostrar solo las filas donde exista al menos un valor nulo
df[df.isnull().any(axis=1)].head(10)

        Fecha  Precip  Evap  Tmax  Tmin
1  1961-01-01     0.0   NaN  25.0  13.0
32 1961-01-02     0.0   NaN  30.0  12.0
60 1961-01-03     0.0   NaN  37.5   9.0
13 1961-01-13     0.0   NaN  32.0  10.0
14 1961-01-14     0.0   NaN  31.0  10.0
15 1961-01-15     0.0   NaN  32.0   8.5
16 1961-01-16     0.0   NaN  31.0  11.0
17 1961-01-17     0.1   NaN  28.0  14.5
18 1961-01-18     0.4   NaN  37.0  17.0
19 1961-01-19    13.5   NaN  23.0  19.5