In [63]:
import pandas as pd
import numpy as np

# Leemos el archivo TXT indicando que:
# skiprows = Sirve para que se salte los primeros 18 renglones de texto informativo
# sep '\s' = Lo usamos para que los datos están separados por espacios en blanco
# names []= Le indicamos los nombres que usaremos para cada columna
# encoding = Utilizamos el formato 'latin-1' para que no fallen los acentos o símbolos
df = pd.read_csv('./Dataset/25001.txt', skiprows=18, sep='\s+', names=['Fecha', 'Precip', 'Evap', 'Tmax', 'Tmin'], encoding='latin-1')

# Mostramos un aviso de que todo salió bien y vemos los primeros 10 renglones
print("Archivo cargado con éxito")
df.head(10)

Archivo cargado con éxito

<>:9: SyntaxWarning: invalid escape sequence '\s'
<>:9: SyntaxWarning: invalid escape sequence '\s'
C:\Users\santi\AppData\Local\Temp\ipykernel_3984\3519410309.py:9: SyntaxWarning: invalid escape sequence '\s'
  df = pd.read_csv('./Dataset/25001.txt', skiprows=18, sep='\s+', names=['Fecha', 'Precip', 'Evap', 'Tmax', 'Tmin'], encoding='latin-1')

        Fecha Precip  Evap    Tmax    Tmin
0       FECHA   (MM)  (MM)  (ï¿½C)  (ï¿½C)
1  01/01/1961      0  Nulo      25      13
2  02/01/1961      0  Nulo    27.5      14
3  03/01/1961      0  Nulo      31      11
4  04/01/1961      0  Nulo      32      13
5  05/01/1961      0  Nulo      29      14
6  06/01/1961      0  Nulo      24    14.5
7  07/01/1961      0  Nulo    28.5      10
8  08/01/1961      0  Nulo      32      12
9  09/01/1961      0  Nulo    33.5      11

In [67]:
# Quitamos la palabra "Nulo"
df = df.replace('Nulo', np.nan)

# Convertimos la columna de fecha a formato datetime
# coerce = Si encuentra basura o texto que no entiende, en lugar de marcar error, simplemente lo marca como NaT
df['Fecha'] = pd.to_datetime(df['Fecha'], errors='coerce')

# Se borran los elementos que no tengan una fecha valida o que sean NaT (Not at Time)
df = df.dropna(subset=['Fecha'])

# Convertimos las columnas de datos a números
cols_num = ['Precip', 'Evap', 'Tmax', 'Tmin']
df[cols_num] = df[cols_num].apply(pd.to_numeric, errors='coerce')

df.head(10)

        Fecha  Precip  Evap  Tmax  Tmin
1  1961-01-01     0.0   NaN  25.0  13.0
2  1961-01-02     0.0   NaN  27.5  14.0
3  1961-01-03     0.0   NaN  31.0  11.0
4  1961-01-04     0.0   NaN  32.0  13.0
5  1961-01-05     0.0   NaN  29.0  14.0
6  1961-01-06     0.0   NaN  24.0  14.5
7  1961-01-07     0.0   NaN  28.5  10.0
8  1961-01-08     0.0   NaN  32.0  12.0
9  1961-01-09     0.0   NaN  33.5  11.0
10 1961-01-10     0.0   NaN  32.5   9.5